name: Tasky CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install

      - name: Verify Core Data Model
        run: |
          MODEL_PATH="Tasky/Tasky.xcdatamodeld"
          CURRENT_VERSION_FILE="$MODEL_PATH/.xccurrentversion"
          if [ ! -d "$MODEL_PATH" ]; then
            echo "Error: Core Data model not found at $MODEL_PATH!"
            exit 1
          fi
          if [ ! -f "$CURRENT_VERSION_FILE" ]; then
            echo "Error: .xccurrentversion file not found at $MODEL_PATH!"
            exit 1
          fi
          CURRENT_VERSION=$(defaults read "$CURRENT_VERSION_FILE" _XCCurrentVersionName)
          if [ "$CURRENT_VERSION" != "Tasky 2.xcdatamodel" ]; then
            echo "Error: Current version in .xccurrentversion file is not 'Tasky 2.xcdatamodel'!"
            exit 1
          fi

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -workspace Tasky.xcworkspace \
            -scheme Tasky \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            ONLY_ACTIVE_ARCH=NO \
            -allowProvisioningUpdates \
            CODE_SIGNING_ALLOWED=NO \
            | xcpretty --report junit --output TestResults.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: TestResults.xml
